get_minute_forecast:
  target:
    entity:
      domain: weather
      integration: nl_weather
      supported_features:
        # TODO: This is a nasty hack, but using "nl_weather.NLWeatherEntityFeature.FORECAST_MINUTE" gives an error
        - climate.ClimateEntityFeature.SWING_MODE