"""Constants for the KNMI Direct integration."""
from typing import Final

from homeassistant.components.weather import (
    ATTR_CONDITION_CLEAR_NIGHT,
    ATTR_CONDITION_CLOUDY,
    ATTR_CONDITION_EXCEPTIONAL,
    ATTR_CONDITION_FOG,
    ATTR_CONDITION_HAIL,
    ATTR_CONDITION_LIGHTNING,
    ATTR_CONDITION_LIGHTNING_RAINY,
    ATTR_CONDITION_PARTLYCLOUDY,
    ATTR_CONDITION_POURING,
    ATTR_CONDITION_RAINY,
    ATTR_CONDITION_SNOWY,
    ATTR_CONDITION_SNOWY_RAINY,
    ATTR_CONDITION_SUNNY,
    ATTR_CONDITION_WINDY,
    ATTR_CONDITION_WINDY_VARIANT, ATTR_WEATHER_HUMIDITY, ATTR_WEATHER_DEW_POINT, ATTR_WEATHER_PRESSURE,
    ATTR_WEATHER_TEMPERATURE, ATTR_WEATHER_VISIBILITY, ATTR_WEATHER_WIND_BEARING, ATTR_WEATHER_WIND_GUST_SPEED,
    ATTR_WEATHER_WIND_SPEED, ATTR_WEATHER_CLOUD_COVERAGE,
)

DOMAIN = "knmi_direct"

CONF_EDR_API_TOKEN: Final = "edr_api_token"
CONF_WMS_TOKEN: Final = "wms_token"
CONF_MQTT_TOKEN: Final = "mqtt_token"

CONDITION_CLASSES: dict[str, list[int]] = {
    ATTR_CONDITION_CLOUDY: [1, 2, 3, 10],
    ATTR_CONDITION_FOG: [20, 30, 32, 33, 34, 35], # TODO: Consider visibility range?
    ATTR_CONDITION_HAIL: [21, 22, 89],
    ATTR_CONDITION_LIGHTNING: [12, 90, 91, 94, ],
    ATTR_CONDITION_LIGHTNING_RAINY: [26, 92, 93, 95, 96],
    ATTR_CONDITION_POURING: [18, 42, 63, 66, 83, 84],
    ATTR_CONDITION_RAINY: [21, 22, 23, 40, 41, 50, 50.5, 51, 52, 53, 54, 55, 56, 57, 58, 60, 60.5, 61, 62, 64, 65,
                           80, 81, 82, 84],
    ATTR_CONDITION_SNOWY: [24, 70, 70.5, 71, 72, 73, 74, 75, 76, 77, 78, 85, 86, 87],
    ATTR_CONDITION_SNOWY_RAINY: [25, 67, 68],
    ATTR_CONDITION_SUNNY: [0],
    ATTR_CONDITION_WINDY: [], # TODO: Take wind in account
    ATTR_CONDITION_WINDY_VARIANT: [],
    ATTR_CONDITION_EXCEPTIONAL: [4,5],
}
CONDITION_MAP = {
    cond_code: cond_ha
    for cond_ha, cond_codes in CONDITION_CLASSES.items()
    for cond_code in cond_codes
}

ATTR_WEATHER_CONDITION = "condition"

PARAMETER_ATTRIBUTE_MAP = {
    ATTR_WEATHER_HUMIDITY : 'rh',
    ATTR_WEATHER_DEW_POINT: 'td',
    ATTR_WEATHER_PRESSURE: 'pp',
    ATTR_WEATHER_TEMPERATURE: 'ta',
    ATTR_WEATHER_VISIBILITY: 'vv',
    ATTR_WEATHER_WIND_BEARING: 'dd',
    ATTR_WEATHER_WIND_GUST_SPEED: 'gff',
    ATTR_WEATHER_WIND_SPEED: 'ff',
    ATTR_WEATHER_CLOUD_COVERAGE: 'n',
    ATTR_WEATHER_CONDITION: 'ww'

}